import { useState, useEffect } from 'react'
import api from '../../api/client'

// ── Health colour helper ──────────────────────────────────────────────────────
function healthColor(val) {
  if (!val) return { color: '#86a98a', bg: '#1a2e1d', border: '#243d28' }
  const v = val.toLowerCase()
  if (v.includes('critical') || v.includes('high') || v.includes('low') && v.includes('tank'))
    return { color: '#f87171', bg: '#7f1d1d22', border: '#991b1b' }
  if (v.includes('warning') || v.includes('medium') || v.includes('water'))
    return { color: '#fbbf24', bg: '#78350f22', border: '#92400e' }
  return { color: '#4ade80', bg: '#14532d22', border: '#166534' }
}

function riskColor(level) {
  if (level === 'High')   return '#f87171'
  if (level === 'Medium') return '#fbbf24'
  return '#4ade80'
}

// ── Big prediction card ───────────────────────────────────────────────────────
function PredCard({ icon, title, member, label, confidence, extra, isAlert }) {
  const c = isAlert
    ? { color: '#f87171', bg: '#7f1d1d22', border: '#991b1b' }
    : { color: '#4ade80', bg: '#14532d22', border: '#166534' }

  return (
    <div style={{ ...styles.predCard, background: c.bg, borderColor: c.border }}>
      <div style={styles.predTop}>
        <span style={{ fontSize: '22px' }}>{icon}</span>
        <span style={styles.memberTag}>{member}</span>
      </div>
      <div style={styles.predTitle}>{title}</div>
      <div style={{ ...styles.predLabel, color: c.color }}>{label}</div>
      <div style={styles.predConf}>
        <div style={styles.confBar}>
          <div style={{ ...styles.confFill, width: `${confidence}%`, background: c.color }} />
        </div>
        <span style={{ fontFamily: "'DM Mono',monospace", fontSize: '12px', color: c.color }}>
          {confidence}% confident
        </span>
      </div>
      {extra && <div style={styles.predExtra}>{extra}</div>}
    </div>
  )
}

// ── Probability bar row ───────────────────────────────────────────────────────
function ProbRow({ label, value, color }) {
  return (
    <div style={{ marginBottom: '8px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '3px' }}>
        <span style={{ fontSize: '12px', color: '#86a98a' }}>{label}</span>
        <span style={{ fontFamily: "'DM Mono',monospace", fontSize: '12px', color }}>{value}%</span>
      </div>
      <div style={styles.barBg}>
        <div style={{ ...styles.barFill, width: `${value}%`, background: color }} />
      </div>
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────
export default function AIPredictions() {
  const [data, setData]       = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError]     = useState(null)
  const [lastUpdated, setLastUpdated] = useState(null)

  const fetchPredictions = async () => {
    try {
      setError(null)
      const res = await api.get('/predict/gardener')
      setData(res.data)
      setLastUpdated(new Date())
    } catch (e) {
      setError('Could not load predictions. Make sure model files are in backend/src/models/')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchPredictions()
    const interval = setInterval(fetchPredictions, 30000)
    return () => clearInterval(interval)
  }, [])

  if (loading) return <div style={styles.loader}>🤖 Running AI models...</div>
  if (error)   return <div style={styles.errBox}>{error}</div>
  if (!data)   return null

  const ph  = data.plant_health   || {}
  const wn  = data.watering_need  || {}
  const td  = data.tank_depletion || {}
  const rs  = data.risk_score     || {}

  const phProbs = ph.probabilities || {}
  const PROB_COLORS = { Healthy: '#4ade80', Warning: '#fbbf24', Critical: '#f87171' }

  return (
    <div>
      {/* Header */}
      <div style={styles.header}>
        <div>
          <h1 style={styles.title}>AI Predictions</h1>
          <p style={styles.sub}>
            Based on sensor reading at {data.based_on_timestamp?.replace('T', ' ').slice(0, 16)}
            {lastUpdated && ` · Refreshed ${lastUpdated.toLocaleTimeString()}`}
          </p>
        </div>
        <button onClick={fetchPredictions} style={styles.refreshBtn}>↻ Refresh</button>
      </div>

      {/* Info banner */}
      <div style={styles.infoBanner}>
        <span style={{ fontSize: '14px' }}>🤖</span>
        <span style={{ fontSize: '12px', color: '#86a98a' }}>
          These predictions are generated by trained Machine Learning models using your live sensor data.
          They update every 30 seconds automatically.
        </span>
      </div>

      {/* 4 Prediction Cards */}
      <div style={styles.cardGrid}>

        {/* 1 — Plant Health */}
        <PredCard
          icon="🌿"
          title="Plant Health"
          member="· Random Forest"
          label={ph.prediction || '—'}
          confidence={ph.confidence || 0}
          isAlert={ph.prediction === 'Critical' || ph.prediction === 'Warning'}
          extra={
            ph.prediction === 'Critical'
              ? '⚠ Immediate attention required'
              : ph.prediction === 'Warning'
              ? 'Monitor closely'
              : 'Plant is doing well'
          }
        />

        {/* 2 — Watering Need */}
        <PredCard
          icon="💧"
          title="Watering Need (next 1 hour)"
          member="· Random Forest"
          label={wn.label || '—'}
          confidence={wn.confidence || 0}
          isAlert={wn.needs_water === true}
          extra={
            wn.needs_water
              ? `Soil moisture: ${data.current_readings?.soil_moisture?.toFixed(1)}% — consider watering now`
              : `Soil moisture: ${data.current_readings?.soil_moisture?.toFixed(1)}% — no action needed`
          }
        />

        {/* 3 — Tank Depletion */}
        <PredCard
          icon="🪣"
          title="Water Tank (next 2 hours)"
          member="· Random Forest"
          label={td.label || '—'}
          confidence={td.confidence || 0}
          isAlert={td.will_run_low === true}
          extra={
            td.will_run_low
              ? `Tank at ${data.current_readings?.water_level?.toFixed(1)}% — refill soon`
              : `Tank at ${data.current_readings?.water_level?.toFixed(1)}% — sufficient`
          }
        />

        {/* 4 — Risk Score */}
        <div style={{ ...styles.predCard, background: '#161f18', borderColor: '#243d28' }}>
          <div style={styles.predTop}>
            <span style={{ fontSize: '22px' }}>📈</span>
            <span style={styles.memberTag}>· XGBoost</span>
          </div>
          <div style={styles.predTitle}>Risk Score Forecast</div>
          <div style={{ display: 'flex', alignItems: 'flex-end', gap: '12px', margin: '8px 0' }}>
            <div style={{ fontFamily: "'DM Mono',monospace", fontSize: '36px', fontWeight: '500', color: riskColor(rs.level), lineHeight: 1 }}>
              {rs.predicted ?? '—'}
            </div>
            <div style={{ paddingBottom: '4px' }}>
              <div style={{ fontSize: '11px', color: '#86a98a' }}>predicted</div>
              <div style={{ fontSize: '12px', color: '#4a6b4e' }}>current: {rs.actual}</div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
            <span style={{ ...styles.trendBadge, color: riskColor(rs.level), borderColor: riskColor(rs.level) + '44', background: riskColor(rs.level) + '11' }}>
              {rs.trend}
            </span>
            <span style={{ ...styles.trendBadge, color: riskColor(rs.level), borderColor: riskColor(rs.level) + '44', background: riskColor(rs.level) + '11' }}>
              {rs.level} Risk
            </span>
          </div>
          <div style={styles.predExtra}>
            {rs.level === 'High' ? '⚠ High risk — check plant conditions' :
             rs.level === 'Medium' ? 'Monitor conditions closely' :
             'Risk level is low — all good'}
          </div>
        </div>

      </div>

      {/* Plant Health Probability Breakdown */}
      {Object.keys(phProbs).length > 0 && (
        <div style={styles.section}>
          <div style={styles.sectionTitle}>Plant Health — Probability Breakdown</div>
          <div style={styles.sectionSub}>How confident is the AI in each possible health state?</div>
          <div style={styles.probCard}>
            {Object.entries(phProbs).map(([cls, pct]) => (
              <ProbRow key={cls} label={cls} value={pct} color={PROB_COLORS[cls] || '#86a98a'} />
            ))}
          </div>
        </div>
      )}

      {/* Current sensor context */}
      <div style={styles.section}>
        <div style={styles.sectionTitle}>Sensor Readings Used for Predictions</div>
        <div style={styles.sectionSub}>These are the live values the AI models analysed</div>
        <div style={styles.contextGrid}>
          {[
            { label: 'Soil Moisture', val: data.current_readings?.soil_moisture, unit: '%', color: '#4ade80' },
            { label: 'Temperature',   val: data.current_readings?.temperature,   unit: '°C', color: '#f97316' },
            { label: 'Humidity',      val: data.current_readings?.humidity,       unit: '%', color: '#60a5fa' },
            { label: 'Water Level',   val: data.current_readings?.water_level,   unit: '%', color: '#22d3ee' },
            { label: 'Light',         val: data.current_readings?.light_lux,     unit: 'lux', color: '#fbbf24' },
          ].map(item => (
            <div key={item.label} style={styles.contextCard}>
              <div style={{ fontSize: '10px', color: '#4a6b4e', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '4px' }}>{item.label}</div>
              <div style={{ fontFamily: "'DM Mono',monospace", fontSize: '20px', color: item.color }}>
                {item.val?.toFixed(1) ?? '—'}<span style={{ fontSize: '11px', opacity: 0.7 }}>{item.unit}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

const styles = {
  loader: { padding: '40px', color: '#86a98a', fontFamily: "'DM Mono',monospace" },
  errBox: { padding: '20px', color: '#f87171', background: '#7f1d1d22', border: '1px solid #991b1b', borderRadius: '12px', fontSize: '13px' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '16px' },
  title:  { fontSize: '22px', fontWeight: '700', color: '#e8f5e9', letterSpacing: '-0.03em' },
  sub:    { fontSize: '12px', color: '#4a6b4e', marginTop: '3px', fontFamily: "'DM Mono',monospace" },
  refreshBtn: { background: '#0d1f12', border: '1px solid #243d28', borderRadius: '8px', padding: '8px 16px', color: '#4ade80', fontFamily: "'Outfit',sans-serif", fontSize: '13px', cursor: 'pointer' },
  infoBanner: { display: 'flex', alignItems: 'center', gap: '10px', background: '#161f18', border: '1px solid #243d28', borderRadius: '10px', padding: '12px 16px', marginBottom: '20px' },
  cardGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(260px, 1fr))', gap: '16px', marginBottom: '24px' },
  predCard: { border: '1px solid', borderRadius: '14px', padding: '20px', display: 'flex', flexDirection: 'column', gap: '8px' },
  predTop:  { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  memberTag: { fontSize: '10px', color: '#4a6b4e', fontFamily: "'DM Mono',monospace", background: '#0d1410', border: '1px solid #1a2e1d', borderRadius: '6px', padding: '2px 8px' },
  predTitle: { fontSize: '12px', fontWeight: '600', color: '#86a98a', textTransform: 'uppercase', letterSpacing: '0.05em' },
  predLabel: { fontSize: '22px', fontWeight: '700', letterSpacing: '-0.02em' },
  predConf:  { display: 'flex', flexDirection: 'column', gap: '4px' },
  confBar:   { height: '3px', background: '#1a2e1d', borderRadius: '9999px', overflow: 'hidden' },
  confFill:  { height: '100%', borderRadius: '9999px', transition: 'width 0.4s' },
  predExtra: { fontSize: '11px', color: '#4a6b4e', marginTop: '2px' },
  trendBadge: { fontSize: '11px', fontWeight: '600', padding: '3px 10px', borderRadius: '9999px', border: '1px solid' },
  section:      { marginBottom: '20px' },
  sectionTitle: { fontWeight: '600', fontSize: '15px', color: '#e8f5e9', marginBottom: '3px' },
  sectionSub:   { fontSize: '11px', color: '#4a6b4e', marginBottom: '12px', fontFamily: "'DM Mono',monospace" },
  probCard:   { background: '#161f18', border: '1px solid #243d28', borderRadius: '12px', padding: '20px', maxWidth: '480px' },
  barBg:      { height: '6px', background: '#1a2e1d', borderRadius: '9999px', overflow: 'hidden' },
  barFill:    { height: '100%', borderRadius: '9999px', transition: 'width 0.5s' },
  contextGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: '12px' },
  contextCard: { background: '#161f18', border: '1px solid #243d28', borderRadius: '10px', padding: '14px' },
}
